import React from 'react';

const EthicsScreen = () => {
  return (
    <div style={styles.container}>
      <div style={styles.textContainer}>
        <p style={styles.text}>
        TERMS AND CONDITIONS
By using the posture-detecting flowerpot system ("PowerPuffPlants"), you agree to the following terms and conditions:

Consent to Data Collection and Video Recording

You agree to be filmed by the integrated camera within the flowerpot system for the purpose of posture detection and feedback.
The video recording will be used exclusively for posture analysis and improvement of user experience.

Data Storage and Usage

The system may collect and store information related to your posture, including video footage and analytical data generated by the system.
All data collected, including video recordings, will be stored securely within the system.
The data will be used solely for providing real-time feedback on your posture, issuing notifications, and generating personalized fragrance rewards.

Data Confidentiality and Privacy

Your data will not be shared, sold, or distributed to any third parties.
The collected data, including video recordings, will remain private and confidential.
Only authorized personnel involved in maintaining the system will have access to the data for the sole purpose of ensuring its functionality and improving the user experience.

Data Retention

Your data, including video recordings, will be stored for the duration necessary to fulfill the purpose of posture detection and feedback.
Upon request, your data can be deleted or anonymized in accordance with applicable privacy laws.

Security

Reasonable measures will be taken to protect your data from unauthorized access, loss, or misuse.
However, no system is completely secure, and by using the system, you acknowledge and accept the inherent risks of data transmission and storage.

Revocation of Consent

You may revoke your consent to being filmed or having your data stored at any time by discontinuing the use of the posture-detecting flowerpot system.
If you choose to withdraw consent, all associated data will be deleted from the system within a reasonable period of time.

System Limitations

The posture-detecting flowerpot system is designed to provide feedback and recommendations based on your posture. It is not intended as a medical device or a replacement for professional health advice.
The system’s data is for personal improvement and well-being purposes only, and no liability is assumed for any health outcomes related to posture.

Changes to Terms

These terms may be updated periodically to reflect changes in system functionality, data storage practices, or legal requirements. Users will be notified of any significant changes.

By using the posture-detecting flowerpot system, you acknowledge that you have read, understood, and agreed to these terms and conditions.
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </div>
    </div>
  );
};

const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    padding: '20px',
  },
  textContainer: {
    marginBottom: '20px',
  },
  text: {
    fontSize: '16px',
    lineHeight: '24px',
  },
  link: {
    color: 'white',
    textDecoration: 'none',
  },
};

export default EthicsScreen;